export const enum Key {
  UseGetManagedMentorDetails = 'use_get_managed_mentor_details',
  UseGetManagedMemberDetails = 'use_get_managed_member_details',
  UseGetProfile = 'use_get_profile',
  UseGetMentorEditProfile = 'use_get_mentor_profile',
  useGetMentorProfileUpdateRequestDetails = 'use_get_mentor_profile_update_details',
  UseGetUpdateMentorProfileInfoRequest = 'use_get_update_mentor_profile_info_request',
  UseMutationProcessRegisterRequest = 'use_mutation_process_register_request',
  useMutationProcessManagerRequestEditMentor = 'use_mutation_process_manager_request_edit_mentor',
  useMutationProcessUpdateMentorProfileRequest = 'use_mutation_process_update_mentor_profile_request',
  UseMutationUpdateDegreeRequest = 'use_mutation_update_degree_request',
  UseMutationUpdateMentorProfileRequest = 'use_mutation_update_mentor_profile_request',
  UseSearchManagedUser = 'use_search_managed_user',
  UseSearchRegisterRequest = 'use_search_register_request',
}
