export const enum ClassStatusType {
  REQUESTING = 'REQUESTING',
  WAITING = 'WAITING',
  EDITREQUEST = 'EDITREQUEST',
  REJECTED = 'REJECTED',
  NOTSTART = 'NOTSTART',
  STARTING = 'STARTING',
  ENDED = 'ENDED',
  CANCEL = 'CANCEL',
  ALL = 'ALL',
}
